export const GAME_CONFIG = {
  width: 1280,
  height: 720,
  pixelArt: true,
  tileSize: 16,
  roomWidth: 40, // tiles
  roomHeight: 30, // tiles
};

export const PLAYER_CONFIG = {
  speed: 150,
  maxHealth: 100,
  dashSpeed: 400,
  dashDuration: 200,
  dashCooldown: 1000,
  invincibilityTime: 500,
};

export const WEAPON_CONFIGS = {
  pistol: {
    name: 'Pistol',
    damage: 10,
    fireRate: 300,
    projectileSpeed: 400,
    ammo: Infinity,
    maxAmmo: Infinity,
    spread: 0,
    projectileCount: 1,
    piercing: false,
    explosive: false,
  },
  smg: {
    name: 'SMG',
    damage: 6,
    fireRate: 100,
    projectileSpeed: 450,
    ammo: 300,
    maxAmmo: 300,
    spread: 10,
    projectileCount: 1,
    piercing: false,
    explosive: false,
  },
  shotgun: {
    name: 'Shotgun',
    damage: 8,
    fireRate: 800,
    projectileSpeed: 350,
    ammo: 40,
    maxAmmo: 40,
    spread: 25,
    projectileCount: 6,
    piercing: false,
    explosive: false,
  },
  sniper: {
    name: 'Sniper Rifle',
    damage: 50,
    fireRate: 1200,
    projectileSpeed: 800,
    ammo: 30,
    maxAmmo: 30,
    spread: 0,
    projectileCount: 1,
    piercing: true,
    explosive: false,
  },
  laser: {
    name: 'Laser Rifle',
    damage: 15,
    fireRate: 50,
    projectileSpeed: 600,
    ammo: 200,
    maxAmmo: 200,
    spread: 0,
    projectileCount: 1,
    piercing: true,
    explosive: false,
  },
  rocket: {
    name: 'Rocket Launcher',
    damage: 40,
    fireRate: 1500,
    projectileSpeed: 300,
    ammo: 20,
    maxAmmo: 20,
    spread: 0,
    projectileCount: 1,
    piercing: false,
    explosive: true,
    explosionRadius: 80,
  },
  lightning: {
    name: 'Lightning Gun',
    damage: 25,
    fireRate: 400,
    projectileSpeed: 500,
    ammo: 50,
    maxAmmo: 50,
    spread: 0,
    projectileCount: 1,
    piercing: false,
    explosive: false,
    chain: true,
    chainCount: 3,
    chainRange: 150,
  },
};

export const ENEMY_CONFIGS = {
  chaser: {
    name: 'Chaser',
    health: 30,
    speed: 80,
    damage: 10,
    attackRange: 30,
    attackCooldown: 1000,
    xp: 10,
    color: 0xff4444,
  },
  shooter: {
    name: 'Shooter',
    health: 20,
    speed: 60,
    damage: 5,
    attackRange: 250,
    attackCooldown: 1500,
    xp: 15,
    color: 0x4444ff,
    projectileSpeed: 200,
  },
  tank: {
    name: 'Tank',
    health: 100,
    speed: 40,
    damage: 20,
    attackRange: 40,
    attackCooldown: 2000,
    xp: 30,
    color: 0x44ff44,
  },
  splitter: {
    name: 'Splitter',
    health: 40,
    speed: 70,
    damage: 8,
    attackRange: 30,
    attackCooldown: 1000,
    xp: 20,
    color: 0xffff44,
    splitCount: 2,
  },
  teleporter: {
    name: 'Teleporter',
    health: 25,
    speed: 100,
    damage: 12,
    attackRange: 35,
    attackCooldown: 800,
    xp: 25,
    color: 0xff44ff,
    teleportCooldown: 3000,
  },
  spawner: {
    name: 'Spawner',
    health: 60,
    speed: 0,
    damage: 0,
    attackRange: 0,
    attackCooldown: 5000,
    xp: 40,
    color: 0x44ffff,
    spawnType: 'chaser',
    maxSpawns: 3,
  },
};

export const BIOMES = {
  facility: {
    name: 'Facility',
    theme: 'tech',
    floorColor: 0x333333,
    wallColor: 0x666666,
    enemies: ['chaser', 'shooter', 'teleporter'],
    difficulty: 1.0,
  },
  caves: {
    name: 'Caves',
    theme: 'organic',
    floorColor: 0x4a3520,
    wallColor: 0x2a1f10,
    enemies: ['chaser', 'splitter', 'tank'],
    difficulty: 1.3,
  },
  factory: {
    name: 'Factory',
    theme: 'industrial',
    floorColor: 0x555555,
    wallColor: 0x888888,
    enemies: ['shooter', 'tank', 'spawner'],
    difficulty: 1.6,
  },
  void: {
    name: 'Void',
    theme: 'surreal',
    floorColor: 0x1a0033,
    wallColor: 0x330066,
    enemies: ['teleporter', 'spawner', 'splitter', 'tank'],
    difficulty: 2.0,
  },
};

export const UPGRADE_CONFIGS = [
  { id: 'maxHealth', name: 'Max Health +20', stat: 'maxHealth', value: 20 },
  { id: 'damage', name: 'Damage +15%', stat: 'damageMultiplier', value: 0.15 },
  { id: 'fireRate', name: 'Fire Rate +20%', stat: 'fireRateMultiplier', value: 0.2 },
  { id: 'speed', name: 'Movement Speed +15%', stat: 'speedMultiplier', value: 0.15 },
  { id: 'projectileSpeed', name: 'Projectile Speed +25%', stat: 'projectileSpeedMultiplier', value: 0.25 },
  { id: 'pierce', name: 'Piercing Shots', stat: 'piercing', value: true },
  { id: 'multishot', name: 'Extra Projectile', stat: 'extraProjectiles', value: 1 },
  { id: 'lifeSteal', name: 'Life Steal 10%', stat: 'lifeSteal', value: 0.1 },
  { id: 'critChance', name: 'Crit Chance +15%', stat: 'critChance', value: 0.15 },
  { id: 'dashCooldown', name: 'Dash Cooldown -30%', stat: 'dashCooldownReduction', value: 0.3 },
];

